### ISSUE TITLE
No file named 'environments' in 'diffuser'

### ISSUE THREAD

**Issue by xiao-zy19** [dbsxodud-11/GTG#1]
I am currently trying to reproduce the algorithm. When I run the code 'python train.py', it comes up with the error:

Traceback (most recent call last):
  File "train.py", line 5, in <module>
    from scripts.train import main
  File "/home/x/GTG/scripts/train.py", line 1, in <module>
    import diffuser.utils as utils
  File "/home/x/GTG/diffuser/__init__.py", line 1, in <module>
    from . import environments
ImportError: cannot import name 'environments' from 'diffuser' (/home/x/GTG/diffuser/__init__.py)

What shall I do to reproduce this repository?

**Comment by xiao-zy19** [comment]
Also, 'python construct_trajectories.py' comes with error:

Traceback (most recent call last):
File "construct_trajectories.py", line 9, in <module>
    from utils import set_seed
ModuleNotFoundError: No module named 'utils'

**Comment by dbsxodud-11** [comment]
Thank you for your interest in our work!

I find some import errors and minor issues while cleaning up the code. Sorry for the inconvenience.
I fixed the bug and updated the code. If the problem persists, please tell me in this issue
